// XCStrings file structure types
export interface XCStringsFile {
  sourceLanguage: string;
  strings: Record<string, XCString>;
  version: string;
}

export interface XCString {
  comment?: string;
  isCommentAutoGenerated?: boolean;
  shouldTranslate?: boolean;
  localizations?: Record<string, XCStringLocalization>;
}

export interface XCStringLocalization {
  stringUnit?: {
    state: string;
    value: string;
  };
  variations?: {
    plural?: Record<string, XCStringVariation>;
    device?: Record<string, XCStringVariation>;
  };
}

export interface XCStringVariation {
  stringUnit?: {
    state: string;
    value: string;
  };
}

// App state types
export interface TranslationState {
  currentStep: number;
  xcstringsData: XCStringsFile | null;
  originalJson: string;
  sourceLanguage: string;
  availableLanguages: string[];
  selectedLanguages: string[];
  excludedStrings: Set<string>; // String keys marked as "do not translate"
  apiKey: string;
  saveApiKey: boolean;
  selectedModel: string;
  appContext: string; // Optional context about the app for better translations
  translationProgress: Record<string, LanguageProgress>;
  isTranslating: boolean;
}

export interface LanguageProgress {
  languageCode: string;
  languageName: string;
  totalStrings: number;
  translatedStrings: number;
  failedStrings: number;
  inProgress: boolean;
  error?: string;
}

export interface TranslatableString {
  key: string;
  value: string;
  comment?: string;
  shouldTranslate: boolean;
  hasPlaceholders: boolean;
  existingTranslations: Record<string, string>;
}

export interface TranslationRequest {
  stringKey: string;
  sourceText: string;
  targetLanguage: string;
  targetLanguageName: string;
  comment?: string;
  placeholders: string[];
  appContext?: string; // Optional context about the app
}

export interface TranslationResult {
  stringKey: string;
  targetLanguage: string;
  translatedText: string;
  success: boolean;
  error?: string;
}

export interface LanguageOption {
  code: string;
  name: string;
  native: string;
}

